import animate from 'tailwindcss-animate'

export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        border: 'var(--border)',
        'input-bg': 'var(--input-bg)',
        'text-background': 'var(--text-background)',
        scrollbar: 'var(--scrollbar)',
        'status-success': 'var(--status-success)',
        'status-success-bg': 'var(--status-success-bg)',
        'status-success-hover': 'var(--status-success-hover)',
        'status-warning': 'var(--status-warning)',
        'status-warning-bg': 'var(--status-warning-bg)',
        'status-warning-hover': 'var(--status-warning-hover)',
        'status-error': 'var(--status-error)',
        'status-error-bg': 'var(--status-error-bg)',
        'status-error-hover': 'var(--status-error-hover)',
        'status-info': 'var(--status-info)',
        'status-info-bg': 'var(--status-info-bg)',
        'status-info-hover': 'var(--status-info-hover)',
        'code-bg': 'var(--code-bg)',
        'code-bg-dark': 'var(--code-bg-dark)',
        'code-text': 'var(--code-text)',
        'code-text-muted': 'var(--code-text-muted)',
        'console-bg': 'var(--console-bg)',
        'log-error': 'var(--log-error)',
        'log-warning': 'var(--log-warning)',
        'log-information': 'var(--log-information)',
        'log-debug': 'var(--log-debug)',
        'accent-10': 'var(--accent-10)',
        'accent-20': 'var(--accent-20)',
        'surface-hover-30': 'var(--surface-hover-30)',
        'surface-hover-50': 'var(--surface-hover-50)',
        'text-muted-20': 'var(--text-muted-20)',
        'method-get': '#61affe',
        'method-post': '#49cc90',
        'method-put': '#fca130',
        'method-delete': '#f93e3e',
        'method-patch': '#50e3c2',
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'var(--radius)',
      },
      boxShadow: {
        theme: 'var(--shadow)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'spin-slow': 'spin 20s linear infinite',
      },
    },
  },
  plugins: [animate, require('@tailwindcss/forms')],
}
